import { supabase } from './supabase';

export type SayDoProfile = { id: string; username: string; display_name: string };
export type Friendship = { id: string; requester_id: string; addressee_id: string; status: 'pending' | 'accepted' | 'rejected' | 'cancelled'; created_at: string };

export async function myProfile(): Promise<SayDoProfile | null> { if (!supabase) return null; const { data, error } = await supabase.rpc('saydo_profile_for_current_user'); if (error) throw error; return data as SayDoProfile | null; }
export async function searchProfiles(query: string): Promise<SayDoProfile[]> { if (!supabase || !query.trim()) return []; const { data, error } = await supabase.rpc('saydo_search_profiles', { query: query.trim() }); if (error) throw error; return (data ?? []) as SayDoProfile[]; }
export async function saveProfile(username: string, displayName: string): Promise<void> { if (!supabase) throw new Error('Supabase is not configured'); const userId = (await supabase.auth.getUser()).data.user?.id; if (!userId) throw new Error('Not authenticated'); const { error } = await supabase.from('saydo_profiles').update({ username: username.trim(), display_name: displayName.trim(), updated_at: new Date().toISOString() }).eq('id', userId); if (error) throw error; }
export async function requestFriend(profileId: string): Promise<void> { if (!supabase) throw new Error('Supabase is not configured'); const userId = (await supabase.auth.getUser()).data.user?.id; if (!userId) throw new Error('Not authenticated'); const { error } = await supabase.from('saydo_friendships').insert({ requester_id: userId, addressee_id: profileId }); if (error) throw error; }
export async function listFriendships(userId: string): Promise<Friendship[]> { if (!supabase) return []; const { data, error } = await supabase.from('saydo_friendships').select('*').or(`requester_id.eq.${userId},addressee_id.eq.${userId}`).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []) as Friendship[]; }
export async function decideFriendship(id: string, status: 'accepted' | 'rejected'): Promise<void> { if (!supabase) throw new Error('Supabase is not configured'); const userId = (await supabase.auth.getUser()).data.user?.id; const { error } = await supabase.from('saydo_friendships').update({ status, updated_at: new Date().toISOString() }).eq('id', id).eq('addressee_id', userId ?? ''); if (error) throw error; }
